import{a as C,S as P,i as g}from"./assets/vendor-BjmtRwYh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const M="45145101-fcee514389e5c9851c2eb0c8a",$="https://pixabay.com/api/";async function h(e,r,s){return(await C.get($,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s}})).data}let m;function L(e){const r=document.querySelector(".gallery"),s=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:i,views:w,comments:E,downloads:B})=>`
   <li class="gallery-item">
        <a href="${t}">
          <img src="${a}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p>Likes: ${i}</p>
          <p>Views: ${w}</p>
          <p>Comments: ${E}</p>
          <p>Downloads: ${B}</p>
        </div>
      </li>
  `).join("");r.insertAdjacentHTML("beforeend",s),m?m.refresh():m=new P(".gallery a")}function u(e){g.error({title:"Error",message:e,backgroundColor:"#ef4040",messageColor:"#fff",icon:"far fa-circle-xmark",iconColor:"#fff",position:"topRight",timeout:5e3,close:!0,progressBar:!0})}function O(){const e=document.querySelector(".gallery");e.innerHTML=""}function x(){g.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",icon:"fas fa-info-circle"})}const H=document.querySelector(".search-form"),b=document.getElementById("loader"),p=document.querySelector(".load-more");let d="",n=1;const l=15;let f=0;H.addEventListener("submit",async e=>{if(e.preventDefault(),d=e.target.elements.searchQuery.value.trim(),d===""){u("Please enter a search query.");return}n=1,O(),y(),S();try{const r=await h(d,n,l);f=r.totalHits,f===0?u("Sorry, there are no images matching your search query. Please try again!"):(L(r.hits),r.hits.length<l||n*l>=f?y():v())}catch(r){u(r.message)}finally{q()}});p.addEventListener("click",async()=>{n+=1,S(),y();try{const e=await h(d,n,l);L(e.hits),I(),n*l>=f?(y(),x()):v()}catch(e){u(e.message)}finally{q()}});function S(){b.style.display="block"}function q(){b.style.display="none"}function v(){p.style.display="block"}function y(){p.style.display="none"}function I(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}const c=document.querySelector('input[name="searchQuery"]');c.addEventListener("input",()=>{c.value.trim()!==""?c.style.borderColor="#4e75ff":c.style.borderColor="#808080"});
//# sourceMappingURL=commonHelpers.js.map
