import{a as M,S as $,i as g}from"./assets/vendor-BjmtRwYh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const B="45145101-fcee514389e5c9851c2eb0c8a",C="https://pixabay.com/api/";async function h(r,o,s){return(await M.get(C,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s}})).data}let f;function L(r){const o=document.querySelector(".gallery"),s=r.map(({webformatURL:n,largeImageURL:e,tags:t,likes:a,views:S,comments:w,downloads:P})=>`
   <li class="gallery-item">
        <a href="${e}">
          <img src="${n}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p>Likes: ${a}</p>
          <p>Views: ${S}</p>
          <p>Comments: ${w}</p>
          <p>Downloads: ${P}</p>
        </div>
      </li>
  `).join("");o.insertAdjacentHTML("beforeend",s),f?f.refresh():f=new $(".gallery a")}function c(r){g.error({title:"Error",message:r,backgroundColor:"#ef4040",messageColor:"#fff",icon:"far fa-circle-xmark",iconColor:"#fff",position:"topRight",timeout:5e3,close:!0,progressBar:!0})}function O(){const r=document.querySelector(".gallery");r.innerHTML=""}function x(){g.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",icon:"fas fa-info-circle"})}const I=document.querySelector(".search-form"),b=document.getElementById("loader"),m=document.querySelector(".load-more");let u="",i=1;const d=15;let y=0;I.addEventListener("submit",async r=>{if(r.preventDefault(),u=r.target.elements.searchQuery.value.trim(),u===""){c("Please enter a search query.");return}i=1,O(),p(),q();try{const o=await h(u,i,d);y=o.totalHits,y===0?c("Sorry, there are no images matching your search query. Please try again!"):(L(o.hits),E())}catch(o){c(o.message)}finally{v()}});m.addEventListener("click",async()=>{i+=1,q(),p();try{const r=await h(u,i,d);L(r.hits),i*d>=y?(p(),x()):E()}catch(r){c(r.message)}finally{v()}});function q(){b.style.display="block"}function v(){b.style.display="none"}function E(){m.style.display="block"}function p(){m.style.display="none"}const l=document.querySelector('input[name="searchQuery"]');l.addEventListener("input",()=>{l.value.trim()!==""?l.style.borderColor="#4e75ff":l.style.borderColor="#808080"});
//# sourceMappingURL=commonHelpers.js.map
