import{a as C,S as P,i as g}from"./assets/vendor-BjmtRwYh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const M="45145101-fcee514389e5c9851c2eb0c8a",$="https://pixabay.com/api/";async function h(e,r,n){return(await C.get($,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}})).data}let d;function L(e){const r=document.querySelector(".gallery"),n=e.map(({webformatURL:s,largeImageURL:t,tags:o,likes:a,views:w,comments:E,downloads:B})=>`
   <li class="gallery-item">
        <a href="${t}">
          <img src="${s}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p>Likes: ${a}</p>
          <p>Views: ${w}</p>
          <p>Comments: ${E}</p>
          <p>Downloads: ${B}</p>
        </div>
      </li>
  `).join("");r.insertAdjacentHTML("beforeend",n),d?d.refresh():d=new P(".gallery a")}function c(e){g.error({title:"Error",message:e,backgroundColor:"#ef4040",messageColor:"#fff",icon:"far fa-circle-xmark",iconColor:"#fff",position:"topRight",timeout:5e3,close:!0,progressBar:!0})}function O(){const e=document.querySelector(".gallery");e.innerHTML=""}function x(){g.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",icon:"fas fa-info-circle"})}const H=document.querySelector(".search-form"),b=document.getElementById("loader"),p=document.querySelector(".load-more");let u="",i=1;const f=15;let y=0;H.addEventListener("submit",async e=>{if(e.preventDefault(),u=e.target.elements.searchQuery.value.trim(),u===""){c("Please enter a search query.");return}i=1,O(),m(),S();try{const r=await h(u,i,f);y=r.totalHits,y===0?c("Sorry, there are no images matching your search query. Please try again!"):(L(r.hits),v())}catch(r){c(r.message)}finally{q()}});p.addEventListener("click",async()=>{i+=1,S(),m();try{const e=await h(u,i,f);L(e.hits),I(),i*f>=y?(m(),x()):v()}catch(e){c(e.message)}finally{q()}});function S(){b.style.display="block"}function q(){b.style.display="none"}function v(){p.style.display="block"}function m(){p.style.display="none"}function I(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}const l=document.querySelector('input[name="searchQuery"]');l.addEventListener("input",()=>{l.value.trim()!==""?l.style.borderColor="#4e75ff":l.style.borderColor="#808080"});
//# sourceMappingURL=commonHelpers.js.map
